const LANG = {
  en: {
    "ui.subtitle": "EFFECTS CHAIN FOR AUDIO MASTERING",
    "ui.presets": "PRESETS:",
    "ui.inst.default": "Instruments ->",
    "ui.inst.full": "Full Track",
    "ui.inst.drums": "Drums",
    "ui.inst.guitar": "Guitar / Bass",
    "ui.inst.voices": "Voices",
    "ui.inst.keys": "Keyboards",
    "ui.inst.empty": "Empty project",
    "ui.btn.save": "↓ SAVE",
    "ui.btn.load": "↑ LOAD",
    "ui.source_audio": "SOURCE AUDIO",
    "ui.drop_audio": "DROP AUDIO FILE HERE &nbsp;·&nbsp; OR CLICK TO LOAD",
    "ui.audio_rights": "You must own or have permission to use the audio you process.",
    "ui.no_audio": "— No audio loaded —",
    "ui.editor_empty": "SELECT A MODULE IN THE BOTTOM<br>CHAIN TO EDIT IT",
    "ui.signal_chain": "SIGNAL CHAIN",
    "ui.clear_all": "✕ CLEAR ALL",
    "ui.clear_modules": "✕ CLEAR MODULES",
    "ui.confirm_clear_modules": "Remove all modules from the chain?",
    "ui.drag_here": "← DRAG MODULES HERE →",
    "ui.rack_modules": "RACK MODULES",
    "ui.drag_or_add": "drag or ⊕",
    "ui.cat.all": "ALL MODULES",
    "ui.cat.dyn": "DYNAMICS",
    "ui.cat.fil": "FILTERS",
    "ui.cat.spa": "SPATIAL",
    "ui.cat.sat": "SATURATION",
    "ui.drag_to_bottom": "Drag to bottom chain",
    "ui.click_to_edit": "Click thumbnail to edit",
    "ui.output": "OUTPUT",
    "ui.btn.rst": "RST PEAK",
    "menu.help": "Help",
    "menu.shortcuts": "Keyboard shortcuts",
    "menu.theme": "Day/Night Mode",
    "foot.copyright": "© 2026 Rack4Master. All rights reserved.",
    "foot.privacy": "Privacy",
    "foot.legal": "Legal",
    "foot.terms": "Terms",
    "foot.donate": "Donate",
    "foot.runs_locally": "Runs locally in your browser. No data stored or tracked.",
    "mod.gate": "NOISE GATE",
    "mod.compressor": "COMPRESSOR",
    "mod.limiter": "LIMITER",
    "mod.eq": "EQ 4-BAND",
    "mod.filter": "HPF / LPF",
    "mod.saturator": "SATURATOR",
    "mod.chorus": "CHORUS",
    "mod.flanger": "FLANGER",
    "mod.reverb": "REVERB",
    "mod.delay": "DELAY",
    "mod.widener": "WIDENER",
    "mod.midside": "MID/SIDE",
    "mod.softclipper": "SOFT CLIPPER",
    "mod.exciter": "EXCITER",
    "mod.deesser": "DE-ESSER",
    "mod.deesserpro": "DE-ESSER PRO",
    "mod.multiband": "MULTIBAND COMP.",
    "mod.tremolo": "TREMOLO",
    "ui.inst.group.guitars": "GUITARS",
    "ui.inst.group.pianos": "PIANOS / KEYS",
    "ui.inst.group.vocals": "VOCALS",
    "ui.inst.group.drums": "DRUMS / PERCUSSION",
    "ui.inst.group.orchestral": "ORCHESTRAL",
    "ui.inst.group.mix": "MIX / MASTERING",
    "ui.inst.acoustic_guitar": "Acoustic Guitar",
    "ui.inst.classical_guitar": "Classical Guitar",
    "ui.inst.clean_guitar": "Electric Clean",
    "ui.inst.drive_guitar": "Drive",
    "ui.inst.fuzz_guitar": "Fuzz",
    "ui.inst.metal_guitar": "Metal",
    "ui.inst.grand_piano": "Grand Piano",
    "ui.inst.studio_piano": "Studio Piano",
    "ui.inst.rhodes": "Rhodes / Wurlitzer",
    "ui.inst.synth": "Synthesizer",
    "ui.inst.vocal_main": "Lead Vocal",
    "ui.inst.vocal_male": "Male Solo",
    "ui.inst.vocal_female": "Female Solo",
    "ui.inst.choir": "Choirs",
    "ui.inst.rap": "Rap / Spoken",
    "ui.inst.acoustic_drums": "Acoustic Drums",
    "ui.inst.electronic_drums": "Electronic Drums",
    "ui.inst.percussion": "Percussion",
    "ui.inst.strings": "Strings",
    "ui.inst.brass": "Brass",
    "ui.inst.woodwinds": "Woodwinds",
    "ui.inst.full_mix": "Full Mix",
    "ui.inst.master_bus": "Master Bus",
    "ui.inst.lofi": "Lo‑Fi / Vintage",
    "ui.inst.bass_boost": "Bass Enhancer",
    "modal.privacy": "<strong>Last updated: May 2026</strong><br><br>Rack4Master is a browser-based audio mastering application designed to operate entirely on the user's device.<br><br><strong>1. Local Processing</strong><br>All audio processing takes place locally within the user's browser using standard web technologies such as the Web Audio API. Audio files selected by users are never uploaded, transmitted, or stored on any server.<br><br><strong>2. No Personal Data Collection</strong><br>Rack4Master does not collect, store, analyze, or process personal data.<br><br><strong>3. No Accounts</strong><br>The application does not require user registration, login, or identity verification.<br><br><strong>4. No Analytics or Tracking</strong><br>This website does not use:<ul><li>analytics platforms</li><li>tracking technologies</li><li>advertising systems</li><li>profiling tools</li></ul><strong>5. Cookies</strong><br>Rack4Master does not set cookies. External services accessed voluntarily by users (such as donation platforms) may use their own cookies independently.<br><br><strong>6. Third-Party Services</strong><br>If users choose to support the project through external payment providers, those services operate under their own privacy policies.<br><br><strong>7. User Responsibility</strong><br>Because all processing occurs locally, users retain full control over their files and data.<br><br><strong>8. Contact</strong><br>Privacy inquiries: <a href='mailto:rackmaster@proton.me' style='color:var(--amber)'>rackmaster@proton.me</a>",
    "modal.legal": "<b>Rack4Master</b> is an independent software project.<br><br><strong>Project name:</strong> Rack4Master<br><strong>Project type:</strong> Browser-based audio mastering tool<br><strong>Contact:</strong> <a href='mailto:rackmaster@proton.me' style='color:var(--amber)'>rackmaster@proton.me</a><br><br>This website provides software tools intended for local use within the user's browser. The project is published under an editorial project identity. Public disclosure of personal identity is not required except where mandated by applicable law. All content is provided for informational and software usage purposes only.<br><br><strong>Open Source License</strong><br>The source code of this application is released under the <strong>MIT License</strong>. You can view, modify, and distribute the code freely. The official repository is available at: <a href='https://github.com/rack4master/rack4master' target='_blank' style='color:var(--amber)'>https://github.com/rack4master/rack4master</a>",
    "modal.terms": "By using Rack4Master, you agree to the following terms.<br><br><strong>1. Software Nature</strong><br>Rack4Master is experimental audio processing software provided free of charge.<br><br><strong>2. Local Operation</strong><br>The software runs entirely within the user's browser. The project does not access, monitor, or store user files.<br><br><strong>3. No Warranty</strong><br>The software is provided 'as is', without warranties of any kind. No guarantee is made regarding audio quality, compatibility, or availability. Users are responsible for maintaining backups.<br><br><strong>4. Limitation of Liability</strong><br>Rack4Master and its author shall not be liable for data loss, audio degradation or indirect damages.<br><br><strong>5. Copyright & User Responsibility</strong><br>Users are solely responsible for ensuring they possess the necessary rights or permissions to process any audio material. The project assumes no responsibility for copyright infringement by users.<br><br><strong>6. Acceptable Use</strong><br>Users agree not to use the software for unlawful purposes.<br><br><strong>7. Changes</strong><br>The project may modify or discontinue the software at any time without notice.<br><br><strong>8. Governing Law and Jurisdiction</strong><br>These terms are governed by the laws of Spain. Any dispute arising from the use of the software shall be submitted to the courts of Spain.",
    "modal.donate": "<strong>Support the Project</strong><br><br>Rack4Master is free software. If you find the project useful, you may voluntarily support its development through donations.<br><br><strong>Nature of Contributions</strong><br>Donations are voluntary contributions intended solely to support the continuation of the project. Donations do not grant ownership rights, exclusive features or contractual obligations. All contributions are optional and non-refundable. External payment platforms operate independently under their own terms."
  },
  es: {
    "ui.subtitle": "CADENA DE EFECTOS PARA MASTERING DE AUDIO",
    "ui.presets": "PRESETS:",
    "ui.inst.default": "Instrumentos ->",
    "ui.inst.full": "Pista completa",
    "ui.inst.drums": "Batería (Drums)",
    "ui.inst.guitar": "Guitarra / Bajo",
    "ui.inst.voices": "Voces",
    "ui.inst.keys": "Teclados",
    "ui.inst.empty": "Proyecto vacío",
    "ui.btn.save": "↓ GUARDAR",
    "ui.btn.load": "↑ CARGAR",
    "ui.source_audio": "AUDIO ORIGINAL",
    "ui.drop_audio": "ARRASTRA TU ARCHIVO DE AUDIO AQUÍ &nbsp;·&nbsp; O HAZ CLIC PARA CARGAR",
    "ui.audio_rights": "Debes poseer o tener permiso para usar el audio que procesas.",
    "ui.no_audio": "— No hay audio cargado —",
    "ui.editor_empty": "SELECCIONA UN MÓDULO EN LA CADENA<br>INFERIOR PARA EDITARLO",
    "ui.signal_chain": "CADENA DE SEÑAL",
    "ui.clear_all": "✕ LIMPIAR TODO",
    "ui.clear_modules": "✕ ELIMINAR MÓDULOS",
    "ui.confirm_clear_modules": "¿Eliminar todos los módulos de la cadena?",
    "ui.drag_here": "← ARRASTRA MÓDULOS AQUÍ →",
    "ui.rack_modules": "MÓDULOS DEL RACK",
    "ui.drag_or_add": "arrastra o ⊕",
    "ui.cat.all": "TODOS LOS MÓDULOS",
    "ui.cat.dyn": "DINÁMICA",
    "ui.cat.fil": "FILTROS",
    "ui.cat.spa": "ESPACIAL",
    "ui.cat.sat": "SATURACIÓN",
    "ui.drag_to_bottom": "Arrastra a la cadena inferior",
    "ui.click_to_edit": "Clic en miniatura para editar",
    "ui.output": "SALIDA",
    "ui.btn.rst": "RST PICO",
    "menu.help": "Ayuda",
    "menu.shortcuts": "Atajos de teclado",
    "menu.theme": "Modo Día/Noche",
    "foot.copyright": "© 2026 Rack4Master. Todos los derechos reservados.",
    "foot.privacy": "Privacidad",
    "foot.legal": "Legal",
    "foot.terms": "Términos",
    "foot.donate": "Donar",
    "foot.runs_locally": "Se ejecuta localmente en tu navegador. No guarda datos ni rastrea.",
    "mod.gate": "PUERTA DE RUIDO",
    "mod.compressor": "COMPRESOR",
    "mod.limiter": "LIMITADOR",
    "mod.eq": "ECUALIZADOR 4-B",
    "mod.filter": "FILTRO HP/LP",
    "mod.saturator": "SATURADOR",
    "mod.chorus": "CHORUS",
    "mod.flanger": "FLANGER",
    "mod.reverb": "REVERB",
    "mod.delay": "DELAY",
    "mod.widener": "ENSANCHADOR",
    "mod.midside": "MID/SIDE",
    "mod.softclipper": "SOFT CLIPPER",
    "mod.exciter": "EXCITADOR ARMÓNICO",
    "mod.deesser": "DE-ESSER",
    "mod.deesserpro": "DE-ESSER PRO",
    "mod.multiband": "COMP. MULTIBANDA",
    "mod.tremolo": "TREMOLO",
    "ui.inst.group.guitars": "GUITARRAS",
    "ui.inst.group.pianos": "PIANOS / TECLADOS",
    "ui.inst.group.vocals": "VOCES",
    "ui.inst.group.drums": "BATERÍA / PERCUSIÓN",
    "ui.inst.group.orchestral": "ORQUESTAL",
    "ui.inst.group.mix": "MEZCLA / MASTERING",
    "ui.inst.acoustic_guitar": "Guitarra acústica",
    "ui.inst.classical_guitar": "Guitarra clásica",
    "ui.inst.clean_guitar": "Eléctrica Clean",
    "ui.inst.drive_guitar": "Drive",
    "ui.inst.fuzz_guitar": "Fuzz",
    "ui.inst.metal_guitar": "Metal",
    "ui.inst.grand_piano": "Gran Piano",
    "ui.inst.studio_piano": "Piano Estudio",
    "ui.inst.rhodes": "Rhodes / Wurlitzer",
    "ui.inst.synth": "Sintetizador",
    "ui.inst.vocal_main": "Voz principal",
    "ui.inst.vocal_male": "Solista hombre",
    "ui.inst.vocal_female": "Solista mujer",
    "ui.inst.choir": "Coros",
    "ui.inst.rap": "Rap / Spoken",
    "ui.inst.acoustic_drums": "Batería acústica",
    "ui.inst.electronic_drums": "Batería electrónica",
    "ui.inst.percussion": "Percusión",
    "ui.inst.strings": "Cuerdas",
    "ui.inst.brass": "Vientos Metal",
    "ui.inst.woodwinds": "Vientos Madera",
    "ui.inst.full_mix": "Mezcla completa",
    "ui.inst.master_bus": "Bus de Mastering",
    "ui.inst.lofi": "Lo‑Fi / Vintage",
    "ui.inst.bass_boost": "Refuerzo de graves",
    "modal.privacy": "<strong>Última actualización: Mayo 2026</strong><br><br>Rack4Master es una aplicación de masterización de audio basada en el navegador, diseñada para funcionar completamente en el dispositivo del usuario.<br><br><strong>1. Procesamiento Local</strong><br>Todo el procesamiento de audio se realiza localmente en el navegador del usuario mediante tecnologías web estándar. Los archivos de audio seleccionados nunca se suben ni se almacenan en ningún servidor.<br><br><strong>2. Sin Recopilación de Datos</strong><br>Rack4Master no recopila ni procesa datos personales.<br><br><strong>3. Sin Cuentas</strong><br>La aplicación no requiere registro ni inicio de sesión.<br><br><strong>4. Sin Analíticas</strong><br>Este sitio web no utiliza plataformas de analítica, rastreo ni publicidad.<br><br><strong>5. Cookies</strong><br>Rack4Master no utiliza cookies.<br><br><strong>8. Contacto</strong><br>Consultas: <a href='mailto:rackmaster@proton.me' style='color:var(--amber)'>rackmaster@proton.me</a>",
    "modal.legal": "<b>Rack4Master</b> es un proyecto de software independiente.<br><br><strong>Nombre:</strong> Rack4Master<br><strong>Tipo:</strong> Herramienta de mastering en navegador<br><strong>Contacto:</strong> <a href='mailto:rackmaster@proton.me' style='color:var(--amber)'>rackmaster@proton.me</a><br><br>Este sitio proporciona herramientas para uso local. El proyecto se publica bajo una identidad de proyecto editorial. No se requiere la divulgación de identidad personal salvo mandato legal.<br><br><strong>Licencia de Código Abierto</strong><br>El código fuente de esta aplicación se distribuye bajo la <strong>Licencia MIT</strong>. Puedes ver, modificar y distribuir el código libremente. El repositorio oficial está disponible en: <a href='https://github.com/rack4master/rack4master' target='_blank' style='color:var(--amber)'>https://github.com/rack4master/rack4master</a>",
    "modal.terms": "Al usar Rack4Master, aceptas los siguientes términos.<br><br><strong>1. Naturaleza del Software</strong><br>Software experimental gratuito.<br><br><strong>2. Operación Local</strong><br>Se ejecuta íntegramente en el navegador. El proyecto no accede ni monitoriza tus archivos.<br><br><strong>3. Sin Garantía</strong><br>El software se proporciona 'tal cual'. El usuario es responsable de sus copias de seguridad.<br><br><strong>4. Limitación de Responsabilidad</strong><br>No nos hacemos responsables de la pérdida de datos o degradación del audio.<br><br><strong>5. Derechos de Autor</strong><br>El usuario es el único responsable de tener los permisos necesarios para procesar el material de audio.<br><br><strong>6. Uso Aceptable</strong><br>El usuario acepta no utilizar el software para fines ilegales.<br><br><strong>7. Cambios</strong><br>El proyecto puede modificar o discontinuar el software en cualquier momento sin previo aviso.<br><br><strong>8. Ley Aplicable y Jurisdicción</strong><br>Estos términos se rigen por las leyes de España. Cualquier disputa derivada del uso del software se someterá a los juzgados de España.",
    "modal.donate": "<strong>Apoya el Proyecto</strong><br><br>Rack4Master es software gratuito. Si te resulta útil, puedes apoyar voluntariamente su desarrollo.<br><br>Las donaciones son voluntarias y no otorgan derechos de propiedad ni funciones exclusivas. No son reembolsables."
  },
  ca: {
    "ui.subtitle": "CADENA D'EFECTES PER A MASTERING D'ÀUDIO",
    "ui.presets": "PRESETS:",
    "ui.inst.default": "Instruments ->",
    "ui.inst.full": "Pista completa",
    "ui.inst.drums": "Bateria (Drums)",
    "ui.inst.guitar": "Guitarra / Baix",
    "ui.inst.voices": "Veus",
    "ui.inst.keys": "Teclats",
    "ui.inst.empty": "Projecte buit",
    "ui.btn.save": "↓ DESAR",
    "ui.btn.load": "↑ CARREGAR",
    "ui.source_audio": "ÀUDIO ORIGINAL",
    "ui.drop_audio": "ARROSSEGA EL TEU FITXER D'ÀUDIO AQUÍ &nbsp;·&nbsp; O FES CLIC PER CARREGAR",
    "ui.audio_rights": "Has de posseir o tenir permís per utilitzar l'àudio que processis.",
    "ui.no_audio": "— No hi ha àudio carregat —",
    "ui.editor_empty": "SELECCIONA UN MÒDUL A LA CADENA<br>INFERIOR PER EDITAR-LO",
    "ui.signal_chain": "CADENA DE SENYAL",
    "ui.clear_all": "✕ NETEJAR TOT",
    "ui.clear_modules": "✕ ELIMINAR MÒDULS",
    "ui.confirm_clear_modules": "Eliminar tots els mòduls de la cadena?",
    "ui.drag_here": "← ARROSSEGA MÒDULS AQUÍ →",
    "ui.rack_modules": "MÒDULS DEL RACK",
    "ui.drag_or_add": "arrossega o ⊕",
    "ui.cat.all": "TOTS ELS MÒDULS",
    "ui.cat.dyn": "DINÀMICA",
    "ui.cat.fil": "FILTRES",
    "ui.cat.spa": "ESPAIAL",
    "ui.cat.sat": "SATURACIÓ",
    "ui.drag_to_bottom": "Arrossega a la cadena inferior",
    "ui.click_to_edit": "Clic a la miniatura per editar",
    "ui.output": "SORTIDA",
    "ui.btn.rst": "RST PIC",
    "menu.help": "Ajuda",
    "menu.shortcuts": "Dreceres de teclat",
    "menu.theme": "Mode Dia/Nit",
    "foot.copyright": "© 2026 Rack4Master. Tots els drets reservats.",
    "foot.privacy": "Privadesa",
    "foot.legal": "Legal",
    "foot.terms": "Termes",
    "foot.donate": "Donar",
    "foot.runs_locally": "S'executa localment al teu navegador. No desa dades ni rastreja.",
    "mod.gate": "P. SOROLL",
    "mod.compressor": "COMPRESSOR",
    "mod.limiter": "LIMITADOR",
    "mod.eq": "EQ 4-BAND",
    "mod.filter": "FILTRE HP/LP",
    "mod.saturator": "SATURADOR",
    "mod.chorus": "CHORUS",
    "mod.flanger": "FLANGER",
    "mod.reverb": "REVERB",
    "mod.delay": "DELAY",
    "mod.widener": "EIXAMPLADOR",
    "mod.midside": "MID/SIDE",
    "mod.softclipper": "SOFT CLIPPER",
    "mod.exciter": "EXCITADOR HARMÒNIC",
    "mod.deesser": "DE-ESSER",
    "mod.deesserpro": "DE-ESSER PRO",
    "mod.multiband": "COMP. MULTIBANDA",
    "mod.tremolo": "TRÈMOLO",
    "ui.inst.group.guitars": "GUITARRES",
    "ui.inst.group.pianos": "PIANOS / TECLATS",
    "ui.inst.group.vocals": "VEUS",
    "ui.inst.group.drums": "BATERIA / PERCUSSIÓ",
    "ui.inst.group.orchestral": "ORQUESTRAL",
    "ui.inst.group.mix": "MESCLA / MASTERING",
    "ui.inst.acoustic_guitar": "Guitarra acústica",
    "ui.inst.classical_guitar": "Guitarra clàssica",
    "ui.inst.clean_guitar": "Elèctrica Clean",
    "ui.inst.drive_guitar": "Drive",
    "ui.inst.fuzz_guitar": "Fuzz",
    "ui.inst.metal_guitar": "Metal",
    "ui.inst.grand_piano": "Gran Piano",
    "ui.inst.studio_piano": "Piano Estudi",
    "ui.inst.rhodes": "Rhodes / Wurlitzer",
    "ui.inst.synth": "Sintetitzador",
    "ui.inst.vocal_main": "Veu principal",
    "ui.inst.vocal_male": "Solista home",
    "ui.inst.vocal_female": "Solista dona",
    "ui.inst.choir": "Cors",
    "ui.inst.rap": "Rap / Spoken",
    "ui.inst.acoustic_drums": "Bateria acústica",
    "ui.inst.electronic_drums": "Bateria electrònica",
    "ui.inst.percussion": "Percussió",
    "ui.inst.strings": "Cordes",
    "ui.inst.brass": "Vents Metall",
    "ui.inst.woodwinds": "Vents Fusta",
    "ui.inst.full_mix": "Mescla completa",
    "ui.inst.master_bus": "Bus de Mastering",
    "ui.inst.lofi": "Lo‑Fi / Vintage",
    "ui.inst.bass_boost": "Reforç de greus",
    "modal.privacy": "<strong>Última actualització: Maig 2026</strong><br><br>Rack4Master és una aplicació de masterització d'àudio que funciona completament al dispositiu de l'usuari.<br><br>L'àudio mai es puja a cap servidor. No recopilem dades ni utilitzem galetes ni sistemes de rastreig.",
    "modal.legal": "<b>Rack4Master</b> és un projecte de software independent.<br><br><strong>Contacte:</strong> <a href='mailto:rackmaster@proton.me' style='color:var(--amber)'>rackmaster@proton.me</a><br><br><strong>Llicència de Codi Obert</strong><br>El codi font d'aquesta aplicació es distribueix sota la <strong>Llicència MIT</strong>. Pots veure, modificar i distribuir el codi lliurement. El repositori oficial està disponible a: <a href='https://github.com/rack4master/rack4master' target='_blank' style='color:var(--amber)'>https://github.com/rack4master/rack4master</a>",
    "modal.terms": "En fer servir Rack4Master acceptes els termes següents.<br><br><strong>1. Naturalesa del Programari</strong><br>Programari experimental gratuït.<br><br><strong>2. Operació Local</strong><br>S'executa íntegrament al navegador. El projecte no accedeix ni monitoritza els teus fitxers.<br><br><strong>3. Sense Garantia</strong><br>El programari es proporciona 'tal qual'. L'usuari és responsable de les seves còpies de seguretat.<br><br><strong>4. Limitació de Responsabilitat</strong><br>No ens fem responsables de la pèrdua de dades o degradació de l'àudio.<br><br><strong>5. Drets d'Autor</strong><br>L'usuari és l'únic responsable de tenir els permisos necessaris per processar el material d'àudio.<br><br><strong>6. Ús Acceptable</strong><br>L'usuari accepta no utilitzar el programari per a fins il·legals.<br><br><strong>7. Canvis</strong><br>El projecte pot modificar o discontinuar el programari en qualsevol moment sense previ avís.<br><br><strong>8. Llei Aplicable i Jurisdicció</strong><br>Aquests termes es regeixen per les lleis d'Espanya. Qualsevol disputa derivada de l'ús del programari se sotmetrà als jutjats d'Espanya.",
    "modal.donate": "<strong>Suport al Projecte</strong><br><br>Si t'agrada l'eina, pots ajudar voluntàriament a la seva continuïtat."
  }
};
