const LANG = {
  en: {
    "ui.subtitle": "EFFECTS CHAIN FOR AUDIO MASTERING",
    "ui.presets": "PRESETS:",
    "ui.inst.default": "Instruments ->",
    "ui.inst.full": "Full Track",
    "ui.inst.drums": "Drums",
    "ui.inst.guitar": "Guitar / Bass",
    "ui.inst.voices": "Voices",
    "ui.inst.keys": "Keyboards",
    "ui.inst.empty": "Empty project",
    "ui.btn.save": "↓ SAVE",
    "ui.btn.load": "↑ LOAD",
    "ui.source_audio": "SOURCE AUDIO",
    "ui.drop_audio": "DROP AUDIO FILE HERE &nbsp;·&nbsp; OR CLICK TO LOAD",
    "ui.audio_rights": "You must own or have permission to use the audio you process.",
    "ui.no_audio": "— No audio loaded —",
    "ui.editor_empty": "SELECT A MODULE IN THE BOTTOM<br>CHAIN TO EDIT IT",
    "ui.signal_chain": "SIGNAL CHAIN",
    "ui.clear_all": "✕ CLEAR ALL",
    "ui.drag_here": "← DRAG MODULES HERE →",
    "ui.rack_modules": "RACK MODULES",
    "ui.drag_or_add": "drag or ⊕",
    "ui.cat.all": "ALL MODULES",
    "ui.cat.dyn": "DYNAMICS",
    "ui.cat.fil": "FILTERS",
    "ui.cat.spa": "SPATIAL",
    "ui.cat.sat": "SATURATION",
    "ui.drag_to_bottom": "Drag to bottom chain",
    "ui.click_to_edit": "Click thumbnail to edit",
    "ui.output": "OUTPUT",
    "ui.btn.rst": "RST PEAK",
    "menu.help": "Help",
    "menu.theme": "Day/Night Mode",
    "foot.copyright": "© 2026 Rack4Master. All rights reserved.",
    "foot.privacy": "Privacy",
    "foot.legal": "Legal",
    "foot.terms": "Terms",
    "foot.donate": "Donate",
    "foot.runs_locally": "Runs locally in your browser. No data stored or tracked.",
    "mod.gate": "NOISE GATE",
    "mod.compressor": "COMPRESSOR",
    "mod.limiter": "LIMITER",
    "mod.eq": "EQ 4-BAND",
    "mod.filter": "HPF / LPF",
    "mod.saturator": "SATURATOR",
    "modal.privacy": "<strong>Last updated: May 2026</strong><br><br>Rack4Master is a browser-based audio mastering application designed to operate entirely on the user's device.<br><br><strong>1. Local Processing</strong><br>All audio processing takes place locally within the user's browser using standard web technologies such as the Web Audio API. Audio files selected by users are never uploaded, transmitted, or stored on any server.<br><br><strong>2. No Personal Data Collection</strong><br>Rack4Master does not collect, store, analyze, or process personal data.<br><br><strong>3. No Accounts</strong><br>The application does not require user registration, login, or identity verification.<br><br><strong>4. No Analytics or Tracking</strong><br>This website does not use:<ul><li>analytics platforms</li><li>tracking technologies</li><li>advertising systems</li><li>profiling tools</li></ul><strong>5. Cookies</strong><br>Rack4Master does not set cookies. External services accessed voluntarily by users (such as donation platforms) may use their own cookies independently.<br><br><strong>6. Third-Party Services</strong><br>If users choose to support the project through external payment providers, those services operate under their own privacy policies.<br><br><strong>7. User Responsibility</strong><br>Because all processing occurs locally, users retain full control over their files and data.<br><br><strong>8. Contact</strong><br>Privacy inquiries: <a href='mailto:rackmaster@proton.me' style='color:var(--amber)'>rackmaster@proton.me</a>",
    "modal.legal": "Rack4Master is an independent software project.<br><br><strong>Project name:</strong> Rack4Master<br><strong>Project type:</strong> Browser-based audio mastering tool<br><strong>Contact:</strong> <a href='mailto:rackmaster@proton.me' style='color:var(--amber)'>rackmaster@proton.me</a><br><br>This website provides software tools intended for local use within the user's browser. The project is published under an editorial project identity. Public disclosure of personal identity is not required except where mandated by applicable law. All content is provided for informational and software usage purposes only.",
    "modal.terms": "By using Rack4Master, you agree to the following terms.<br><br><strong>1. Software Nature</strong><br>Rack4Master is experimental audio processing software provided free of charge.<br><br><strong>2. Local Operation</strong><br>The software runs entirely within the user's browser. The project does not access, monitor, or store user files.<br><br><strong>3. No Warranty</strong><br>The software is provided 'as is', without warranties of any kind. No guarantee is made regarding audio quality, compatibility, or availability. Users are responsible for maintaining backups.<br><br><strong>4. Limitation of Liability</strong><br>Rack4Master and its author shall not be liable for data loss, audio degradation or indirect damages.<br><br><strong>5. Copyright & User Responsibility</strong><br>Users are solely responsible for ensuring they possess the necessary rights or permissions to process any audio material. The project assumes no responsibility for copyright infringement by users.<br><br><strong>6. Acceptable Use</strong><br>Users agree not to use the software for unlawful purposes.<br><br><strong>7. Changes</strong><br>The project may modify or discontinue the software at any time without notice.",
    "modal.donate": "<strong>Support the Project</strong><br><br>Rack4Master is free software. If you find the project useful, you may voluntarily support its development through donations.<br><br><strong>Nature of Contributions</strong><br>Donations are voluntary contributions intended solely to support the continuation of the project. Donations do not grant ownership rights, exclusive features or contractual obligations. All contributions are optional and non-refundable. External payment platforms operate independently under their own terms."
  },
  es: {
    "ui.subtitle": "CADENA DE EFECTOS PARA MASTERING DE AUDIO",
    "ui.presets": "PRESETS:",
    "ui.inst.default": "Instrumentos ->",
    "ui.inst.full": "Pista completa",
    "ui.inst.drums": "Batería (Drums)",
    "ui.inst.guitar": "Guitarra / Bajo",
    "ui.inst.voices": "Voces",
    "ui.inst.keys": "Teclados",
    "ui.inst.empty": "Proyecto vacío",
    "ui.btn.save": "↓ GUARDAR",
    "ui.btn.load": "↑ CARGAR",
    "ui.source_audio": "AUDIO ORIGINAL",
    "ui.drop_audio": "ARRASTRA TU ARCHIVO DE AUDIO AQUÍ &nbsp;·&nbsp; O HAZ CLIC PARA CARGAR",
    "ui.audio_rights": "Debes poseer o tener permiso para usar el audio que procesas.",
    "ui.no_audio": "— No hay audio cargado —",
    "ui.editor_empty": "SELECCIONA UN MÓDULO EN LA CADENA<br>INFERIOR PARA EDITARLO",
    "ui.signal_chain": "CADENA DE SEÑAL",
    "ui.clear_all": "✕ LIMPIAR TODO",
    "ui.drag_here": "← ARRASTRA MÓDULOS AQUÍ →",
    "ui.rack_modules": "MÓDULOS DEL RACK",
    "ui.drag_or_add": "arrastra o ⊕",
    "ui.cat.all": "TODOS LOS MÓDULOS",
    "ui.cat.dyn": "DINÁMICA",
    "ui.cat.fil": "FILTROS",
    "ui.cat.spa": "ESPACIAL",
    "ui.cat.sat": "SATURACIÓN",
    "ui.drag_to_bottom": "Arrastra a la cadena inferior",
    "ui.click_to_edit": "Clic en miniatura para editar",
    "ui.output": "SALIDA",
    "ui.btn.rst": "RST PICO",
    "menu.help": "Ayuda",
    "menu.theme": "Modo Día/Noche",
    "foot.copyright": "© 2026 Rack4Master. Todos los derechos reservados.",
    "foot.privacy": "Privacidad",
    "foot.legal": "Legal",
    "foot.terms": "Términos",
    "foot.donate": "Donar",
    "foot.runs_locally": "Se ejecuta localmente en tu navegador. No guarda datos ni rastrea.",
    "mod.gate": "PUERTA DE RUIDO",
    "mod.compressor": "COMPRESOR",
    "mod.limiter": "LIMITADOR",
    "mod.eq": "ECUALIZADOR 4-B",
    "mod.filter": "FILTRO HP/LP",
    "mod.saturator": "SATURADOR",
    "modal.privacy": "<strong>Última actualización: Mayo 2026</strong><br><br>Rack4Master es una aplicación de masterización de audio basada en el navegador, diseñada para funcionar completamente en el dispositivo del usuario.<br><br><strong>1. Procesamiento Local</strong><br>Todo el procesamiento de audio se realiza localmente en el navegador del usuario mediante tecnologías web estándar. Los archivos de audio seleccionados nunca se suben ni se almacenan en ningún servidor.<br><br><strong>2. Sin Recopilación de Datos</strong><br>Rack4Master no recopila ni procesa datos personales.<br><br><strong>3. Sin Cuentas</strong><br>La aplicación no requiere registro ni inicio de sesión.<br><br><strong>4. Sin Analíticas</strong><br>Este sitio web no utiliza plataformas de analítica, rastreo ni publicidad.<br><br><strong>5. Cookies</strong><br>Rack4Master no utiliza cookies.<br><br><strong>8. Contacto</strong><br>Consultas: <a href='mailto:rackmaster@proton.me' style='color:var(--amber)'>rackmaster@proton.me</a>",
    "modal.legal": "Rack4Master es un proyecto de software independiente.<br><br><strong>Nombre:</strong> Rack4Master<br><strong>Tipo:</strong> Herramienta de mastering en navegador<br><strong>Contacto:</strong> <a href='mailto:rackmaster@proton.me' style='color:var(--amber)'>rackmaster@proton.me</a><br><br>Este sitio proporciona herramientas para uso local. El proyecto se publica bajo una identidad de proyecto editorial. No se requiere la divulgación de identidad personal salvo mandato legal.",
    "modal.terms": "Al usar Rack4Master, aceptas los siguientes términos.<br><br><strong>1. Naturaleza del Software</strong><br>Software experimental gratuito.<br><br><strong>2. Operación Local</strong><br>Se ejecuta íntegramente en el navegador. El proyecto no accede ni monitoriza tus archivos.<br><br><strong>3. Sin Garantía</strong><br>El software se proporciona 'tal cual'. El usuario es responsable de sus copias de seguridad.<br><br><strong>4. Limitación de Responsabilidad</strong><br>No nos hacemos responsables de la pérdida de datos o degradación del audio.<br><br><strong>5. Derechos de Autor</strong><br>El usuario es el único responsable de tener los permisos necesarios para procesar el material de audio.",
    "modal.donate": "<strong>Apoya el Proyecto</strong><br><br>Rack4Master es software gratuito. Si te resulta útil, puedes apoyar voluntariamente su desarrollo.<br><br>Las donaciones son voluntarias y no otorgan derechos de propiedad ni funciones exclusivas. No son reembolsables."
  },
  ca: {
    "ui.subtitle": "CADENA D'EFECTES PER A MASTERING D'ÀUDIO",
    "ui.presets": "PRESETS:",
    "ui.inst.default": "Instruments ->",
    "ui.inst.full": "Pista completa",
    "ui.inst.drums": "Bateria (Drums)",
    "ui.inst.guitar": "Guitarra / Baix",
    "ui.inst.voices": "Veus",
    "ui.inst.keys": "Teclats",
    "ui.inst.empty": "Projecte buit",
    "ui.btn.save": "↓ DESAR",
    "ui.btn.load": "↑ CARREGAR",
    "ui.source_audio": "ÀUDIO ORIGINAL",
    "ui.drop_audio": "ARROSSEGA EL TEU FITXER D'ÀUDIO AQUÍ &nbsp;·&nbsp; O FES CLIC PER CARREGAR",
    "ui.audio_rights": "Has de posseir o tenir permís per utilitzar l'àudio que processis.",
    "ui.no_audio": "— No hi ha àudio carregat —",
    "ui.editor_empty": "SELECCIONA UN MÒDUL A LA CADENA<br>INFERIOR PER EDITAR-LO",
    "ui.signal_chain": "CADENA DE SENYAL",
    "ui.clear_all": "✕ NETEJAR TOT",
    "ui.drag_here": "← ARROSSEGA MÒDULS AQUÍ →",
    "ui.rack_modules": "MÒDULS DEL RACK",
    "ui.drag_or_add": "arrossega o ⊕",
    "ui.cat.all": "TOTS ELS MÒDULS",
    "ui.cat.dyn": "DINÀMICA",
    "ui.cat.fil": "FILTRES",
    "ui.cat.spa": "ESPAIAL",
    "ui.cat.sat": "SATURACIÓ",
    "ui.drag_to_bottom": "Arrossega a la cadena inferior",
    "ui.click_to_edit": "Clic a la miniatura per editar",
    "ui.output": "SORTIDA",
    "ui.btn.rst": "RST PIC",
    "menu.help": "Ajuda",
    "menu.theme": "Mode Dia/Nit",
    "foot.copyright": "© 2026 Rack4Master. Tots els drets reservats.",
    "foot.privacy": "Privadesa",
    "foot.legal": "Legal",
    "foot.terms": "Termes",
    "foot.donate": "Donar",
    "foot.runs_locally": "S'executa localment al teu navegador. No desa dades ni rastreja.",
    "mod.gate": "PORTA DE SOROLL",
    "mod.compressor": "COMPRESSOR",
    "mod.limiter": "LIMITADOR",
    "mod.eq": "EQUALITZADOR 4-B",
    "mod.filter": "FILTRE HP/LP",
    "mod.saturator": "SATURADOR",
    "modal.privacy": "<strong>Última actualització: Maig 2026</strong><br><br>Rack4Master és una aplicació de masterització d'àudio que funciona completament al dispositiu de l'usuari.<br><br>L'àudio mai es puja a cap servidor. No recopilem dades ni utilitzem galetes ni sistemes de rastreig.",
    "modal.legal": "Projecte de software independent.<br><br><strong>Contacte:</strong> <a href='mailto:rackmaster@proton.me' style='color:var(--amber)'>rackmaster@proton.me</a>",
    "modal.terms": "En fer servir Rack4Master acceptes que el software es proporciona 'tal com és' i que ets el responsable legal de l'àudio que processis.",
    "modal.donate": "<strong>Suport al Projecte</strong><br><br>Si t'agrada l'eina, pots ajudar voluntàriament a la seva continuïtat."
  }
};
